
const books = [
  {
    id: 1,
    title: 'A Suitable Boy',
    author: 'Vikram Seth',
    subject: 'Fiction',
    publicationYear: 1993,
    genre: 'Family saga',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A vast, panoramic tale charting the fortunes of four large families and exploring India and its rich and varied culture at a crucial point in its history.'
  },
  {
    id: 2,
    title: 'The Discovery of India',
    author: 'Jawaharlal Nehru',
    subject: 'History',
    publicationYear: '1946',
    genre: 'Non-fiction',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: "An insight into India's rich history and culture by the first Prime Minister of India."
  },
  {
    id: 3,
    title: "Midnight's Children",
    author: 'Salman Rushdie',
    subject: 'Fiction',
    publicationYear: '1981',
    genre: 'Postcolonial literature',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of Saleem Sinai, who was born at the stroke of midnight on August 15, 1947, the moment India gained independence from British rule.'
  },
  {
    id: 4,
    title: 'The White Tiger',
    author: 'Aravind Adiga',
    subject: 'Fiction',
    publicationYear: '2008',
    genre: 'Social realism',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of Balram Halwai, a village boy who becomes a successful entrepreneur in the city, while serving as a driver to a wealthy family.'
  },
  {
    id: 5,
    title: 'Train to Pakistan',
    author: 'Khushwant Singh',
    subject: 'Fiction',
    publicationYear: '1956',
    genre: 'Historical fiction',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'Set during the partition of India in 1947, the novel tells the story of a small village that becomes a microcosm of the violence and chaos of the larger event.'
  },
  {
    id: 6,
    title: 'Interpreter of Maladies',
    author: 'Jhumpa Lahiri',
    subject: 'Fiction',
    publicationYear: '1999',
    genre: 'Short stories',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A collection of nine stories that explore themes of love, loss, and cultural identity among Indian immigrants in the United States.'
  },
  {
    id: 7,
    title: 'The Immortals of Meluha',
    author: 'Amish Tripathi',
    subject: 'Fiction',
    publicationYear: '2010',
    genre: 'Fantasy',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The first book in the Shiva Trilogy, a mythological fantasy series that reimagines the legends of the Hindu god Shiva.'
  },
  {
    id: 8,
    title: 'The Palace of Illusions',
    author: 'Chitra Banerjee Divakaruni',
    subject: 'Fiction',
    publicationYear: '2008',
    genre: 'Historical fiction',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A retelling of the Hindu epic Mahabharata from the perspective of Draupadi, the wife of the Pandavas.'
  },
  {
    id: 9,
    title: 'Five Point Someone',
    author: 'Chetan Bhagat',
    subject: 'Fiction',
    publicationYear: '2004',
    genre: 'Drama',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of three friends who struggle to cope with the pressures of the Indian education system.'
  },
  {
    id: 10,
    title: 'The Rozabal Line',
    author: 'Ashwin Sanghi',
    subject: 'Fiction',
    publicationYear: '2007',
    genre: 'Thriller',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A conspiracy thriller that weaves together elements of religion, history, and mythology.'
  },
  {
    id: 11,
    title: 'The Inheritance of Loss',
    author: 'Kiran Desai',
    subject: 'Fiction',
    publicationYear: '2006',
    genre: 'Postcolonial literature',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of an Indian judge living in the Himalayas and his granddaughter who comes to stay with him.'
  },
  {
    id: 12,
    title: 'Shantaram',
    author: 'Gregory David Roberts',
    subject: 'Fiction',
    publicationYear: '2003',
    genre: 'Autobiographical novel',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: "A semi-autobiographical novel based on the author's experiences as a fugitive in Mumbai."
  },
  {
    id: 13,
    title: 'The Great Indian Novel',
    author: 'Shashi Tharoor',
    subject: 'Fiction',
    publicationYear: '1989',
    genre: 'Satire',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A satirical retelling of the Indian epic Mahabharata, with characters from Indian history and politics.'
  },
  {
    id: 14,
    title: 'The Guide',
    author: 'R.K. Narayan',
    subject: 'Fiction',
    publicationYear: '1958',
    genre: 'Drama',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of a tour guide in a small town in South India, who becomes a spiritual guide to a young woman.'
  },
  {
    id: 15,
    title: 'A Fine Balance',
    author: 'Rohinton Mistry',
    subject: 'Fiction',
    publicationYear: '1995',
    genre: 'Historical fiction',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'Set in the backdrop of the Emergency in India, the novel tells the story of four characters from different backgrounds whose lives intersect.'
  },
  {
    id: 16,
    title: 'The Namesake',
    author: 'Jhumpa Lahiri',
    subject: 'Fiction',
    publicationYear: '2003',
    genre: 'Drama',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of a Bengali immigrant family in the United States, and their struggle to balance their Indian and American identities.'
  },
  {
    id: 17,
    title: 'The Oath of the Vayuputras',
    author: 'Amish Tripathi',
    subject: 'Fiction',
    publicationYear: '2013',
    genre: 'Fantasy',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The final book in the Shiva Trilogy, in which the hero Shiva battles to save his kingdom from a great evil.'
  },
  {
    id: 18,
    title: 'Inheritance of Loss',
    author: 'Kiran Desai',
    subject: 'Fiction',
    publicationYear: '2006',
    genre: 'Postcolonial literature',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of an Indian judge living in the Himalayas and his granddaughter who comes to stay with him.'
  },
  {
    id: 19,
    title: 'The Argumentative Indian',
    author: 'Amartya Sen',
    subject: 'Non-fiction',
    publicationYear: '2005',
    genre: 'Essays',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: "A collection of essays that explore India's history, culture, and identity, and the challenges it faces in the modern world."
  },
  {
    id: 20,
    title: 'Sacred Games',
    author: 'Vikram Chandra',
    subject: 'Fiction',
    publicationYear: '2006',
    genre: 'Crime fiction',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of a Mumbai police officer and a gangster, and the complex web of crime and corruption they become entangled in.'
  },
  {
    id: 21,
    title: 'The Lowland',
    author: 'Jhumpa Lahiri',
    subject: 'Fiction',
    publicationYear: '2013',
    genre: 'Historical fiction',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of two brothers from Kolkata, and how their lives diverge when one becomes involved in a political movement.'
  },
  {
    id: 22,
    title: 'The Secret of the Nagas',
    author: 'Amish Tripathi',
    subject: 'Fiction',
    publicationYear: '2011',
    genre: 'Fantasy',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The second book in the Shiva Trilogy, in which the hero Shiva battles against a secret society called the Nagas.'
  },
  {
    id: 23,
    title: 'The Shadow Lines',
    author: 'Amitav Ghosh',
    subject: 'Fiction',
    publicationYear: '1988',
    genre: 'Postcolonial literature',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'The story of two families, one Indian and one English, and the events that connect them across time and space.'
  },
  {
    id: 24,
    title: 'The White Mughals',
    author: 'William Dalrymple',
    subject: 'Non-fiction',
    publicationYear: '2002',
    genre: 'History',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A historical account of the relationship between British colonizers and Indian nobility during the 18th century.'
  },
  {
    id: 25,
    title: 'The Calcutta Chromosome',
    author: 'Amitav Ghosh',
    subject: 'Fiction',
    publicationYear: '1995',
    genre: 'Science fiction',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A novel that combines elements of mystery, science fiction, and history, set in the backdrop of medical research in Kolkata.'
  },
  {
    id: 26,
    title: 'The Glass Palace',
    author: 'Amitav Ghosh',
    subject: 'Fiction',
    publicationYear: '2000',
    genre: 'Historical fiction',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A sweeping epic that spans generations and continents, exploring the lives of characters from Burma, India, and Malaya.'
  },
  {
    id: 27,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    subject: 'Fiction',
    publicationYear: '1925',
    genre: 'Classic',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.'
  },
  {
    id: 28,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    subject: 'Fiction',
    publicationYear: '1960',
    genre: 'Classic',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A story of racial injustice and the destruction of innocence in the American Deep South.'
  },
  {
    id: 29,
    title: '1984',
    author: 'George Orwell',
    subject: 'Fiction',
    publicationYear: '1949',
    genre: 'Dystopian',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A dystopian novel set in a totalitarian society.'
  },
  {
    id: 30,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    subject: 'Fiction',
    publicationYear: '1813',
    genre: 'Romance',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A story of love, reputation, and class in the Georgian era.'
  },
  {
    id: 31,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    subject: 'Fiction',
    publicationYear: '1951',
    genre: 'Coming-of-age',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A story of teenage angst and alienation.'
  },
  {
    id: 32,
    title: 'To the Lighthouse',
    author: 'Virginia Woolf',
    subject: 'Fiction',
    publicationYear: '1927',
    genre: 'Modernist',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A novel that explores the passage of time and the nature of art.'
  },
  {
    id: 33,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    subject: 'Fiction',
    publicationYear: '1937',
    genre: 'Fantasy',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A fantasy adventure novel set in a fictional world.'
  },
  {
    id: 34,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    subject: 'Fiction',
    publicationYear: '1851',
    genre: 'Adventure',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A story of obsession and revenge, centered around the white whale.'
  },
  {
    id: 35,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    subject: 'Fiction',
    publicationYear: '1932',
    genre: 'Dystopian',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A dystopian novel that explores the dangers of a utopian society.'
  },
  {
    id: 36,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    subject: 'Fiction',
    publicationYear: '1954',
    genre: 'Fantasy',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A high fantasy epic set in the fictional world of Middle-earth.'
  },
  {
    id: 37,
    title: 'Jane Eyre',
    author: 'Charlotte Bronte',
    subject: 'Fiction',
    publicationYear: '1847',
    genre: 'Gothic',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A coming-of-age story that follows the experiences of its eponymous heroine.'
  },
  {
    id: 38,
    title: 'The Chronicles of Narnia',
    author: 'C.S. Lewis',
    subject: 'Fiction',
    publicationYear: '1950',
    genre: 'Fantasy',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A series of fantasy novels set in the fictional realm of Narnia.'
  },
  {
    id: 39,
    title: 'The Odyssey',
    author: 'Homer',
    subject: 'Fiction',
    publicationYear: '8th century BC',
    genre: 'Epic',
    language: 'Ancient Greek',
    availibility: 'Available',
    format: 'Print',
    summary: "An epic poem that tells the story of Odysseus' ten-year journey home after the Trojan War."
  },
  {
    id: 40,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    subject: 'Fiction',
    publicationYear: '1890',
    genre: 'Gothic',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A philosophical novel about the consequences of aestheticism and the pursuit of pleasure.'
  },
  {
    id: 41,
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    subject: 'Fiction',
    publicationYear: '1988',
    genre: 'Fantasy',
    language: 'Portuguese',
    availibility: 'Available',
    format: 'Print',
    summary: "A mystical story about following one's dreams and finding one's purpose in life."
  },
  {
    id: 42,
    title: 'The Kite Runner',
    author: 'Khaled Hosseini',
    subject: 'Fiction',
    publicationYear: '2003',
    genre: 'Historical',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: "A story of friendship, betrayal, and redemption set against the backdrop of Afghanistan's turbulent history."
  },
  {
    id: 43,
    title: 'The Count of Monte Cristo',
    author: 'Alexandre Dumas',
    subject: 'Fiction',
    publicationYear: '1844',
    genre: 'Adventure',
    language: 'French',
    availibility: 'Available',
    format: 'Print',
    summary: 'A tale of revenge, love, and redemption.'
  },
  {
    id: 44,
    title: 'The Diary of a Young Girl',
    author: 'Anne Frank',
    subject: 'Non-fiction',
    publicationYear: '1947',
    genre: 'Autobiography',
    language: 'Dutch',
    availibility: 'Available',
    format: 'Print',
    summary: 'The diary of a Jewish girl hiding from the Nazis during World War II.'
  },
  {
    id: 45,
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    subject: 'Fiction',
    publicationYear: '1866',
    genre: 'Psychological',
    language: 'Russian',
    availibility: 'Available',
    format: 'Print',
    summary: 'A psychological novel that explores the themes of guilt, redemption, and moral responsibility.'
  },
  {
    id: 46,
    title: 'The Great Expectations',
    author: 'Charles Dickens',
    subject: 'Fiction',
    publicationYear: '1861',
    genre: 'Classic',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A bildungsroman that depicts the personal growth and development of an orphan named Pip.'
  },
  {
    id: 47,
    title: 'The Little Prince',
    author: 'Antoine de Saint-Exupery',
    subject: 'Fiction',
    publicationYear: '1943',
    genre: "Children's",
    language: 'French',
    availibility: 'Available',
    format: 'Print',
    summary: 'A poetic and philosophical tale about the nature of friendship, love, and loss.'
  },
  {
    id: 48,
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    subject: 'Fiction',
    publicationYear: '1939',
    genre: 'Historical',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: "A story of the Joad family's migration from the Oklahoma Dust Bowl to California during the Great Depression."
  },
  {
    id: 49,
    title: 'The Divine Comedy',
    author: 'Dante Alighieri',
    subject: 'Fiction',
    publicationYear: '1320',
    genre: 'Epic',
    language: 'Italian',
    availibility: 'Available',
    format: 'Print',
    summary: 'An epic poem that follows the journey of the protagonist through Hell, Purgatory, and Paradise.'
  },
  {
    id: 50,
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    subject: 'Fiction',
    publicationYear: '1876',
    genre: 'Adventure',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A story of a young boy growing up along the Mississippi River.'
  },
  {
    id: 51,
    title: 'Les Miserables',
    author: 'Victor Hugo',
    subject: 'Fiction',
    publicationYear: '1862',
    genre: 'Historical',
    language: 'French',
    availibility: 'Available',
    format: 'Print',
    summary: 'A tale of justice, love, and redemption set against the backdrop of 19th-century France.'
  },
  {
    id: 52,
    title: 'The Iliad',
    author: 'Homer',
    subject: 'Fiction',
    publicationYear: '8th century BC',
    genre: 'Epic',
    language: 'Ancient Greek',
    availibility: 'Available',
    format: 'Print',
    summary: 'An ancient Greek epic poem that tells the story of the Trojan War.'
  },
  {
    id: 53,
    title: 'The Girl with the Dragon Tattoo',
    author: 'Stieg Larsson',
    subject: 'Fiction',
    publicationYear: '2005',
    genre: 'Mystery',
    language: 'Swedish',
    availibility: 'Available',
    format: 'Print',
    summary: 'A psychological thriller that follows the investigation of a cold case by a computer hacker and a journalist.'
  },
  {
    id: 54,
    title: 'The Book Thief',
    author: 'Markus Zusak',
    subject: 'Fiction',
    publicationYear: '2005',
    genre: 'Historical',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A story of a young girl living with her foster family in Nazi Germany during World War II.'
  },
  {
    id: 55,
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel Garcia Marquez',
    subject: 'Fiction',
    publicationYear: '1967',
    genre: 'Magical Realism',
    language: 'Spanish',
    availibility: 'Available',
    format: 'Print',
    summary: 'A multi-generational story that follows the Buendia family in the fictional town of Macondo.'
  },
  {
    id: 56,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    subject: 'Fiction',
    publicationYear: '1937',
    genre: 'Fantasy',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A fantasy adventure novel set in a fictional world.'
  },
  {
    id: 57,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    subject: 'Fiction',
    publicationYear: '1851',
    genre: 'Adventure',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A story of obsession and revenge, centered around the white whale.'
  },
  {
    id: 58,
    title: 'Brave New World',
    author: 'Aldous Huxley',
    subject: 'Fiction',
    publicationYear: '1932',
    genre: 'Dystopian',
    language: 'English',
    availibility: 'Available',
    format: 'Print',
    summary: 'A dystopian novel that explores the dangers of a utopian society.'
  },{
    title: "The Amazing Spider-Man",
    author: "Stan Lee",
    subject: "Superheroes",
    publicationYear: "1963",
    genre: "Action, Adventure",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of Peter Parker, a high school student who gains spider-like abilities and becomes the superhero Spider-Man.",
    id: "59"
  },
  {
    title: "Watchmen",
    author: "Alan Moore",
    subject: "Superheroes",
    publicationYear: "1986",
    genre: "Drama, Mystery",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "Set in an alternate history where superheroes exist, the murder of a government-sponsored superhero leads to a group of vigilantes uncovering a conspiracy.",
    id: "60"
  },
  {
    title: "Batman: Year One",
    author: "Frank Miller",
    subject: "Superheroes",
    publicationYear: "1987",
    genre: "Action, Crime",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of Bruce Wayne's first year as Batman and James Gordon's first year with the Gotham City Police Department.",
    id: 61
  },
  {
    title: "Saga",
    author: "Brian K. Vaughan",
    subject: "Fantasy, Science Fiction",
    publicationYear: "2012",
    genre: "Drama, Adventure",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A space opera following a couple from long-warring extraterrestrial races as they flee authorities from both sides of a galactic war.",
    id: 62
  },
  {
    title: "Maus",
    author: "Art Spiegelman",
    subject: "Biography, History",
    publicationYear: "1980",
    genre: "Autobiography, Historical Fiction",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A graphic novel depicting the author's father's experiences as a Polish Jew and Holocaust survivor.",
    id: 63
  },
  {
    title: "The Sandman",
    author: "Neil Gaiman",
    subject: "Fantasy, Horror",
    publicationYear: "1989",
    genre: "Drama, Dark Fantasy",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of Dream, one of the seven Endless, and his interactions with both the mortal and supernatural worlds.",
    id: 64
  },
  {
    title: "Persepolis",
    author: "Marjane Satrapi",
    subject: "Biography, History",
    publicationYear: "2000",
    genre: "Autobiography, Historical Fiction",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A memoir of the author's childhood in Iran during the Islamic Revolution.",
    id: 65
  },
  {
    title: "V for Vendetta",
    author: "Alan Moore",
    subject: "Dystopia, Political",
    publicationYear: "1982",
    genre: "Action, Thriller",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "Set in a future totalitarian England, a masked anarchist fights against the oppressive government.",
    id: 66
  },
  {
    title: "The Walking Dead",
    author: "Robert Kirkman",
    subject: "Horror, Survival",
    publicationYear: "2003",
    genre: "Drama, Post-Apocalyptic",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A post-apocalyptic tale of a group of survivors trying to stay alive in a world overrun by zombies.",
    id: 67
  },
  {
    title: "Y: The Last Man",
    author: "Brian K. Vaughan",
    subject: "Science Fiction",
    publicationYear: "2002",
    genre: "Drama, Adventure",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of Yorick Brown and his pet Capuchin monkey Ampersand, the last two males of any mammal species.",
    id: 68
  },
  {
    title: "Preacher",
    author: "Garth Ennis",
    subject: "Fantasy, Horror",
    publicationYear: "1995",
    genre: "Drama, Supernatural",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of Jesse Custer, a small-town preacher who becomes possessed by a supernatural creature.",
    id: 69
  },
  {
    title: "Fables",
    author: "Bill Willingham",
    subject: "Fantasy",
    publicationYear: "2002",
    genre: "Drama, Adventure",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "Characters from fairy tales and folklore are forced to live in a secret community in modern-day New York City.",
    id: 70
  },
  {
    title: "Sin City",
    author: "Frank Miller",
    subject: "Crime, Noir",
    publicationYear: "1991",
    genre: "Drama, Thriller",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A series of dark and gritty stories set in Basin City, a fictional town filled with corruption and crime.",
    id: 71
  },
  {
    title: "Scott Pilgrim",
    author: "Bryan Lee O'Malley",
    subject: "Romance, Comedy",
    publicationYear: "2004",
    genre: "Action, Slice of Life",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of Scott Pilgrim, a slacker and musician who must defeat his new girlfriend's seven evil exes.",
    id: 72
  },
  {
    title: "The Umbrella Academy",
    author: "Gerard Way",
    subject: "Superheroes",
    publicationYear: "2007",
    genre: "Drama, Science Fiction",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A dysfunctional family of superheroes reunite to solve the mystery of their father's death.",
    id: 73
  },
  {
    title: "Bone",
    author: "Jeff Smith",
    subject: "Fantasy",
    publicationYear: "1991",
    genre: "Adventure, Comedy",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of the Bone cousins, Fone Bone, Phoney Bone, and Smiley Bone, as they get caught up in an epic adventure.",
    id: 74
  },
  {
    title: "Transmetropolitan",
    author: "Warren Ellis",
    subject: "Science Fiction",
    publicationYear: "1997",
    genre: "Drama, Satire",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "Set in a dystopian future, a gonzo journalist fights against corruption and abuses of power.",
    id: 75
  },
  {
    title: "Akira",
    author: "Katsuhiro Otomo",
    subject: "Science Fiction",
    publicationYear: "1982",
    genre: "Action, Cyberpunk",
    language: "Japanese",
    availibility: "Available",
    format: "Print",
    summary: "Set in a post-apocalyptic Tokyo, a biker gang member gains psychic powers and becomes a target of government experiments.",
    id: 76
  },
  {
    title: "Locke & Key",
    author: "Joe Hill",
    subject: "Horror, Fantasy",
    publicationYear: "2008",
    genre: "Drama, Supernatural",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of the Locke siblings, who discover magical keys that unlock various powers and secrets.",
    id: 77
  },
  {
    title: "Sandman Mystery Theatre",
    author: "Matt Wagner",
    subject: "Mystery, Crime",
    publicationYear: "1993",
    genre: "Drama, Historical Fiction",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "Set in 1930s New York City, a vigilante known as the Sandman solves crimes and battles against organized crime.",
    id: 78
  },
  {
    title: "Hellboy",
    author: "Mike Mignola",
    subject: "Horror, Fantasy",
    publicationYear: "1993",
    genre: "Action, Supernatural",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of Hellboy, a half-demon paranormal investigator who works for a secret government organization.",
    id: 79
  },
  {
    title: "The League of Extraordinary Gentlemen",
    author: "Alan Moore",
    subject: "Adventure, Fantasy",
    publicationYear: "1999",
    genre: "Action, Steampunk",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A group of Victorian-era literary characters team up to save the world from various threats.",
    id: 81
  },
  {
    title: "The Wicked + The Divine",
    author: "Kieron Gillen",
    subject: "Fantasy",
    publicationYear: "2014",
    genre: "Drama, Mythology",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "Every 90 years, twelve gods reincarnate as young people, who become pop stars before they die within two years.",
    id: 82
  },
  {
    title: "Saga of the Swamp Thing",
    author: "Alan Moore",
    subject: "Horror, Superheroes",
    publicationYear: "1982",
    genre: "Drama, Dark Fantasy",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "The story of Alec Holland, a scientist turned into a plant-based creature known as the Swamp Thing.",
    id: 83
  },
  {
    title: "The Boys",
    author: "Garth Ennis",
    subject: "Superheroes",
    publicationYear: "2006",
    genre: "Drama, Satire",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A CIA black ops team monitors and controls superheroes who abuse their powers.",
    id: 84
  },
  {
    title: "Fables: Werewolves of the Heartland",
    author: "Bill Willingham",
    subject: "Fantasy",
    publicationYear: "2012",
    genre: "Drama, Adventure",
    language: "English",
    availibility: "Available",
    format: "Print",
    summary: "A standalone story set in the Fables universe, focusing on Bigby Wolf's journey to find a new home for Fabletown.",
    id: 85
  }
]

export {books}